//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wttprojesi.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public byte Siralama { get; set; }
        public short Memur_No { get; set; }
        public string Soyad { get; set; }
        public string Ad { get; set; }
        public string Meslek { get; set; }
        public string Daire { get; set; }
        public string Bolum { get; set; }
        public int Aylik { get; set; }
        public System.DateTime KontrolTarihi { get; set; }
        public System.DateTime ise_Baslama { get; set; }
        public System.DateTime Dogum_Tarihi { get; set; }
        public string kan_grubu { get; set; }
        public string rh { get; set; }
    }
}
